queue_installments_for_capturing:
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  every: 5s
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  class: "InstallmentProcessor"
  queue: installment_queue
  args:
  description: "This job captures all due installments"
